# Generated by Django 4.1.2 on 2023-01-27 18:24

import app1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_centre', models.CharField(max_length=500, verbose_name='Centre de Santé')),
                ('situation', models.CharField(max_length=500, verbose_name='Situation Geographique du Centre')),
            ],
        ),
        migrations.CreateModel(
            name='Officier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.BigIntegerField(default=app1.models.matricul, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('datePriseService', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistreDeces',
            fields=[
                ('numero_registre', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Numero du Registre')),
                ('annee', models.IntegerField(default=2023, verbose_name='Annee')),
            ],
        ),
        migrations.CreateModel(
            name='RegistreMariage',
            fields=[
                ('numero_registre', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Numero du Registre')),
                ('annee', models.IntegerField(default=2023, verbose_name='Annee')),
            ],
        ),
        migrations.CreateModel(
            name='RegistreNaissance',
            fields=[
                ('numero_registre', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Numero du Registre')),
                ('annee', models.IntegerField(default=2023, verbose_name='Annee')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Naissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('HOMME', 'homme'), ('FEMME', 'femme')], default='Masculin', max_length=150, verbose_name='Precise le sexe')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=250, verbose_name='Prenoms')),
                ('date_naiss', models.DateField(null=True, verbose_name='Date de Naissance')),
                ('heure_naiss', models.TimeField(verbose_name='Heure de Naissance')),
                ('pays', models.CharField(default='Algérie', max_length=50, verbose_name='pays de naissance')),
                ('pere', models.CharField(blank=True, max_length=250, verbose_name='Nom et Prénoms du Pere')),
                ('profession_pere', models.CharField(blank=True, max_length=250, verbose_name='Profession du Pere')),
                ('date_naiss_pere', models.DateField(null=True, verbose_name='Date de Naissance')),
                ('lieu_naiss_pere', models.CharField(default='', max_length=250, verbose_name='Lieu de Naissance')),
                ('mere', models.CharField(max_length=250, verbose_name='Nom et Prénoms de la Mere')),
                ('profession_mere', models.CharField(max_length=250, verbose_name='Profession de la Mere')),
                ('date_naiss_mere', models.DateField(null=True, verbose_name='Date de Naissance')),
                ('lieu_naiss_mere', models.CharField(default='', max_length=250, verbose_name='Lieu de Naissance')),
                ('grand_pere_paternel', models.CharField(blank=True, default='', max_length=250, verbose_name='Nom et Prénoms du grand Pere')),
                ('grand_mere_paternel', models.CharField(blank=True, default='', max_length=250, verbose_name='Nom et Prénoms du grand mere')),
                ('grand_pere_maternel', models.CharField(blank=True, default='', max_length=250, verbose_name='Nom et Prénoms du grand Pere')),
                ('grand_mere_maternel', models.CharField(blank=True, default='', max_length=250, verbose_name='Nom et Prénoms du grand mere')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.centre')),
                ('numero_registre', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.registrenaissance')),
                ('officier', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.officier')),
            ],
        ),
        migrations.CreateModel(
            name='Mariage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=app1.models.num_mariage, max_length=5, unique=True)),
                ('nom_requerant1', models.CharField(default=' ', max_length=500, verbose_name='Nom du Marie')),
                ('prenom_requerant1', models.CharField(default=' ', max_length=500, verbose_name='Prenom du Marie')),
                ('profession_req1', models.CharField(max_length=500, verbose_name='Profession du Marie')),
                ('domicile_req1', models.CharField(max_length=500, verbose_name='Lieu de Domicile du Marie')),
                ('date_req1', models.DateField(verbose_name='Date de Naissance du Marie')),
                ('lieu_naiss_req1', models.CharField(max_length=500, verbose_name='Lieu de Naissance du Marie')),
                ('temoin_req1', models.CharField(max_length=250, verbose_name='Nom et Prénoms du Témoin du Marie')),
                ('nom_requerant2', models.CharField(default=' ', max_length=500, verbose_name='Nom du Mariee')),
                ('prenom_requerant2', models.CharField(default=' ', max_length=500, verbose_name='Prenom du Mariee')),
                ('profession_req2', models.CharField(max_length=500, verbose_name='Profession du Mariee')),
                ('domicile_req2', models.CharField(max_length=500, verbose_name='Lieu de Domicile du Mariee')),
                ('date_req2', models.DateField(verbose_name='Date de Naissance du Mariee')),
                ('lieu_naiss_req2', models.CharField(max_length=500, verbose_name='Lieu de Naissance du Mariee')),
                ('temoin_req2', models.CharField(max_length=250, verbose_name='Nom et Prénoms du Témoin du Mariee')),
                ('filiation', models.CharField(default=' ', max_length=500, verbose_name='la filiation')),
                ('date_mariage', models.DateField(verbose_name='Date du Mariage')),
                ('lieu_mariage', models.CharField(max_length=500, verbose_name='Lieu du Mariage')),
                ('numero_registre', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.registremariage')),
                ('officier', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.officier')),
            ],
        ),
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=250, verbose_name='Prenoms')),
                ('sexe', models.CharField(choices=[('HOMME', 'homme'), ('FEMME', 'femme')], default='Masculin', max_length=150, verbose_name='Precise le sexe')),
                ('date_naiss', models.DateField(verbose_name='Date de Naissance')),
                ('lieu_naiss', models.CharField(max_length=250, verbose_name='Lieu de Naissance')),
                ('mariée', models.CharField(choices=[('oui', 'OUI'), ('non', 'NON')], default='NON', max_length=10)),
                ('jour_deces', models.DateField(verbose_name='Date de deces')),
                ('heure_deces', models.TimeField(verbose_name='Heure de deces')),
                ('lieu_deces', models.CharField(max_length=250, verbose_name='Lieu de deces')),
                ('numero_registre', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.registredeces')),
                ('officier', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.officier')),
            ],
        ),
    ]
